name: "oauth2-battle.net package CI"
on:
  push: # if you merge pull request from dev to master, consider as "push"
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 15
        registry-url: 'https://registry.npmjs.org'


    - name: Minimal git conf
      run: git config --global user.email "sylvain.joly00@orange.fr" && git config --global user.name "sylvainSUPINTERNET"

    - name: Update version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install typescript -g
    - run: npm run build-ts
    - run: npm ci
    - run: npm version patch #--no-git-tag-version
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

    - name: Commit & Push
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        